# Generated by Django 4.0.1 on 2022-02-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votevoter',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.vote'),
        ),
        migrations.AddField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vote'),
        ),
    ]
