# Generated by Django 4.0.1 on 2022-02-09 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_vote_end_date_canvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 3, 31, 10, 29226, tzinfo=utc)),
        ),
    ]
