# Generated by Django 3.2.8 on 2022-02-10 01:00

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_vote_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 1, 0, 40, 279533)),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='result',
            field=jsonfield.fields.JSONField(),
        ),
    ]
