# Generated by Django 3.2.8 on 2022-03-15 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220210_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteresult',
            old_name='result',
            new_name='results',
        ),
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 22, 37, 46, 773572)),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vote'),
        ),
    ]
