# Generated by Django 4.0.1 on 2022-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0003_answer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Finished')], default=1),
        ),
    ]
