# Generated by Django 4.0.1 on 2022-05-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0004_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='status',
        ),
    ]
