# Generated by Django 4.0.1 on 2022-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0006_room_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='times_voted',
            field=models.IntegerField(default=0),
        ),
    ]
