# Generated by Django 4.0.1 on 2022-05-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0007_answer_times_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sentanswer',
            name='room',
        ),
    ]
