# Generated by Django 4.0.1 on 2022-05-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0008_remove_sentanswer_question_remove_sentanswer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentanswer',
            name='question',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='sent_answer', to='sitting.question'),
            preserve_default=False,
        ),
    ]
