# Generated by Django 4.0.1 on 2022-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0009_sentanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
